receivers:
  # Receive metrics via OTLP protocol (gRPC and HTTP)
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  # Apache Spark receiver to collect metrics from Spark cluster
  apachespark:
    endpoint: "http://spark-master:4040"
    collection_interval: 30s
    application_names:
      - "AnomalyDetectionApp"

processors:
  # Batch processor to reduce network calls
  batch:
    timeout: 10s
    send_batch_size: 1024
  
  # Memory limiter to prevent OOM
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128
  
  # Resource processor to add custom attributes
  resource:
    attributes:
      - key: deployment.environment
        value: "local"
        action: insert
      - key: service.namespace
        value: "aiops"
        action: insert
  
  # Metrics transform for anomaly detection
  metricstransform:
    transforms:
      - include: .*
        match_type: regexp
        action: update
        operations:
          - action: add_label
            new_label: anomaly_detection_enabled
            new_value: "true"

exporters:
  # Export to Elasticsearch using data streams
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    logs_dynamic_index:
      enabled: true
    traces_dynamic_index:
      enabled: true  
    metrics_dynamic_index:
      enabled: true
    mapping:
      mode: ecs
  
  # Debug exporter to see data in console
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 100

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  
  pprof:
    endpoint: 0.0.0.0:1777
  
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  
  pipelines:
    metrics:
      receivers: [otlp, apachespark]
      processors: [memory_limiter, resource, batch]
      exporters: [elasticsearch, debug]
    
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [elasticsearch, debug]
    
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [elasticsearch, debug]
  
  telemetry:
    logs:
      level: info
    metrics:
      level: detailed
      address: 0.0.0.0:8888
